version: '2'

volumes:
  mosquitto-data: {}
  mosquitto-log: {}
  mosquitto-config: {}

services:
  display:
    build: ./display
    privileged: true
    restart: always

  mosquitto:
    build: ./mosquitto
    volumes:
      - "mosquitto-config:/mosquitto/config"
      - "mosquitto-data:/mosquitto/data"
      #- "mosquitto-log:/mosquitto/log"
    expose:
      - "1883"
      - "9001"
