version: '2'
services:
  display:
    build: ./display
    privileged: true
    restart: always

  mqtt:
    build: ./mqtt
    volumes:
      - "/mqtt/config"
      - "/mqtt/data"
      - "/mqtt/log"
    expose:
      - "1883"
      - "9001"
