version: '2'

volumes:
  mqtt-data:
  mqtt-logs:
  mqtt-config:

services:
  display:
    build: ./display
    privileged: true
    restart: always

  mqtt:
    build: ./mqtt
    volumes:
      - "mqtt-config:/mqtt/config"
      - "mqtt-data:/mqtt/data"
      - "mqtt-log:/mqtt/log"
    expose:
      - "1883"
      - "9001"
