version: '2'

volumes:
  mosquitto-data: {}
  mosquitto-log: {}
  mosquitto-config: {}

services:

  display:
    build: ./display
    privileged: true
    restart: always
    depends_on:
      - mosquitto

  tracker:
    build: ./tracker
    privileged: true
    labels:
      io.resin.features.kernel-modules: '1'
    restart: always
    depends_on:
      - mosquitto
      - gpsd
      - owserver

  mosquitto:
    build: ./mosquitto
    volumes:
      - "mosquitto-config:/mosquitto/config"
      - "mosquitto-data:/mosquitto/data"
      - "mosquitto-log:/mosquitto/log"
    ports:
      - "1883:1883"
      - "9001:9001"

  gpsd:
    build: ./gpsd
    privileged: true
    restart: always

  owserver:
    build: ./owserver
    ports:
      - "2121:2121"
      - "4304:4304"
    labels:
      io.resin.features.kernel-modules: '1'
    privileged: true
